[build]
  publish = "website"
  functions = "netlify/functions"
  command = "npm install"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  functions = "netlify/functions"
  publish = "website"
  port = 8888
